name: Deploy Nuxt VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy na VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.VPS_HOST }}
          username: ${{ vars.VPS_USER }}
          key: ${{ vars.VPS_SSH_KEY }}
          port: ${{ vars.VPS_PORT }}
          script_stop: true
          script: |
            cd /var/www/dvt-emp
            git pull origin main
            npm install
            npm run build
            pm2 restart devt-emp